# Generated by Django 3.2.6 on 2021-08-13 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.IntegerField(choices=[(1, 'FIRST'), (2, 'SECOND'), (3, 'THIRD')], default=1),
        ),
        migrations.AddField(
            model_name='course',
            name='year',
            field=models.CharField(choices=[(1, 'FIRST'), (2, 'SECOND'), (3, 'THIRD'), (4, 'FOURTH'), (5, 'FIFTH'), (6, 'SIXTH'), (7, 'SEVENTH')], default=1, max_length=200),
        ),
    ]
